steps:
  # Step 1: Compile Go app
  - name: 'gcr.io/cloud-builders/go'
    env: ['GOPATH=/gopath']
    args: ['build', '-o', 'main', 'main.go']

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild:v1.0',
        '.'
      ]

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east4-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild:v1.0'
      ]

  # Step 4: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy'
    args: ['-n', 'prod', 'apply', '-f', 'prod/deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east4-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

options:
  logging: CLOUD_LOGGING_ONLY
